//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InterviewTest.HotelService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelsSoap", Namespace="http://ws.design.americaneagle.com")]
    public partial class Hotels : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private HotelCredentials hotelCredentialsValueField;
        
        private ImageOptions imageOptionsValueField;
        
        private System.Threading.SendOrPostCallback GetHotelOperationCompleted;
        
        private FilterContainer filterContainerValueField;
        
        private HotelPagingOptions hotelPagingOptionsValueField;
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SiteScopeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Hotels() {
            this.Url = global::InterviewTest.Properties.Settings.Default.InterviewTest_HotelService_Hotels;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HotelCredentials HotelCredentialsValue {
            get {
                return this.hotelCredentialsValueField;
            }
            set {
                this.hotelCredentialsValueField = value;
            }
        }
        
        public ImageOptions ImageOptionsValue {
            get {
                return this.imageOptionsValueField;
            }
            set {
                this.imageOptionsValueField = value;
            }
        }
        
        public FilterContainer FilterContainerValue {
            get {
                return this.filterContainerValueField;
            }
            set {
                this.filterContainerValueField = value;
            }
        }
        
        public HotelPagingOptions HotelPagingOptionsValue {
            get {
                return this.hotelPagingOptionsValueField;
            }
            set {
                this.hotelPagingOptionsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelCompletedEventHandler GetHotelCompleted;
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event SiteScopeCompletedEventHandler SiteScopeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ImageOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HotelCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.design.americaneagle.com/GetHotel", RequestNamespace="http://ws.design.americaneagle.com", ResponseNamespace="http://ws.design.americaneagle.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel GetHotel(int hotelId) {
            object[] results = this.Invoke("GetHotel", new object[] {
                        hotelId});
            return ((Hotel)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelAsync(int hotelId) {
            this.GetHotelAsync(hotelId, null);
        }
        
        /// <remarks/>
        public void GetHotelAsync(int hotelId, object userState) {
            if ((this.GetHotelOperationCompleted == null)) {
                this.GetHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelOperationCompleted);
            }
            this.InvokeAsync("GetHotel", new object[] {
                        hotelId}, this.GetHotelOperationCompleted, userState);
        }
        
        private void OnGetHotelOperationCompleted(object arg) {
            if ((this.GetHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelCompleted(this, new GetHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HotelCredentialsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HotelPagingOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ImageOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("FilterContainerValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.design.americaneagle.com/GetHotels", RequestNamespace="http://ws.design.americaneagle.com", ResponseNamespace="http://ws.design.americaneagle.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel[] GetHotels() {
            object[] results = this.Invoke("GetHotels", new object[0]);
            return ((Hotel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync() {
            this.GetHotelsAsync(null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[0], this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.design.americaneagle.com/SiteScope", RequestNamespace="http://ws.design.americaneagle.com", ResponseNamespace="http://ws.design.americaneagle.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SiteScope() {
            object[] results = this.Invoke("SiteScope", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SiteScopeAsync() {
            this.SiteScopeAsync(null);
        }
        
        /// <remarks/>
        public void SiteScopeAsync(object userState) {
            if ((this.SiteScopeOperationCompleted == null)) {
                this.SiteScopeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSiteScopeOperationCompleted);
            }
            this.InvokeAsync("SiteScope", new object[0], this.SiteScopeOperationCompleted, userState);
        }
        
        private void OnSiteScopeOperationCompleted(object arg) {
            if ((this.SiteScopeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SiteScopeCompleted(this, new SiteScopeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.design.americaneagle.com", IsNullable=false)]
    public partial class HotelCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CityFilterCity {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MultipleCityFilterCity {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalCodeFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExcludeHotelsFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipleCityFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalCodeRangeFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MerchantOnlyFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateProvinceFilter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public abstract partial class HotelFilter {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class PostalCodeFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CountryFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CityFilter : HotelFilter {
        
        private CityFilterCity valueField;
        
        /// <remarks/>
        public CityFilterCity value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class NameFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class ExcludeHotelsFilter : HotelFilter {
        
        private int[] idsField;
        
        /// <remarks/>
        public int[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MultipleCityFilter : HotelFilter {
        
        private MultipleCityFilterCity[] citiesField;
        
        /// <remarks/>
        public MultipleCityFilterCity[] cities {
            get {
                return this.citiesField;
            }
            set {
                this.citiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class PostalCodeRangeFilter : HotelFilter {
        
        private string postalCodeField;
        
        private int rangeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MerchantOnlyFilter : HotelFilter {
        
        private bool valueField;
        
        /// <remarks/>
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class StateProvinceFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class HotelImage {
        
        private string captionField;
        
        private string uRLField;
        
        private int widthField;
        
        private int heightField;
        
        private string thumbnailURLField;
        
        private int thumbnailHeightField;
        
        private int thumbnailWidthField;
        
        /// <remarks/>
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public string ThumbnailURL {
            get {
                return this.thumbnailURLField;
            }
            set {
                this.thumbnailURLField = value;
            }
        }
        
        /// <remarks/>
        public int ThumbnailHeight {
            get {
                return this.thumbnailHeightField;
            }
            set {
                this.thumbnailHeightField = value;
            }
        }
        
        /// <remarks/>
        public int ThumbnailWidth {
            get {
                return this.thumbnailWidthField;
            }
            set {
                this.thumbnailWidthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class Hotel {
        
        private double distanceField;
        
        private string bookingLinkField;
        
        private HotelImage[] imagesField;
        
        private int hotelIDField;
        
        private string nameField;
        
        private string airportCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double lowRateField;
        
        private double highRateField;
        
        private string marketingLevelField;
        
        private int confidenceField;
        
        private string hotelModifiedField;
        
        private string propertyTypeField;
        
        private string timeZoneField;
        
        private string gMTOffsetField;
        
        private string yearPropertyOpenedField;
        
        private string yearPropertyRenovatedField;
        
        private string nativeCurrencyField;
        
        private int numberOfRoomsField;
        
        private int numberOfSuitesField;
        
        private int numberOfFloorsField;
        
        private string checkInTimeField;
        
        private string checkOutTimeField;
        
        private bool hasValetParkingField;
        
        private bool hasContinentalBreakfastField;
        
        private bool hasInRoomMoviesField;
        
        private bool hasSaunaField;
        
        private bool hasWhirlpoolField;
        
        private bool hasVoiceMailField;
        
        private bool has24HourSecurityField;
        
        private bool hasParkingGarageField;
        
        private bool hasElectronicRoomKeysField;
        
        private bool hasCoffeeTeaMakerField;
        
        private bool hasSafeField;
        
        private bool hasVideoCheckOutField;
        
        private bool hasRestrictedAccessField;
        
        private bool hasInteriorRoomEntranceField;
        
        private bool hasExteriorRoomEntranceField;
        
        private bool hasCombinationField;
        
        private bool hasFitnessFacilityField;
        
        private bool hasGameRoomField;
        
        private bool hasTennisCourtField;
        
        private bool hasGolfCourseField;
        
        private bool hasInHouseDiningField;
        
        private bool hasInHouseBarField;
        
        private bool hasHandicapAccessibleField;
        
        private bool hasChildrenAllowedField;
        
        private bool hasPetsAllowedField;
        
        private bool hasTVInRoomField;
        
        private bool hasDataPortsField;
        
        private bool hasMeetingRoomsField;
        
        private bool hasBusinessCenterField;
        
        private bool hasDryCleaningField;
        
        private bool hasIndoorPoolField;
        
        private bool hasOutdoorPoolField;
        
        private bool hasNonSmokingRoomsField;
        
        private bool hasAirportTransportationField;
        
        private bool hasAirConditioningField;
        
        private bool hasClothingIronField;
        
        private bool hasWakeUpServiceField;
        
        private bool hasMiniBarInRoomField;
        
        private bool hasRoomServiceField;
        
        private bool hasHairDryerField;
        
        private bool hasCarRentDeskField;
        
        private bool hasFamilyRoomsField;
        
        private bool hasKitchenField;
        
        private bool hasMapField;
        
        private string propertyDescriptionField;
        
        private double ratingField;
        
        private string gDSChainCodeField;
        
        private string gDSChaincodeNameField;
        
        private string destinationIDField;
        
        private string drivingDirectionsField;
        
        private string nearbyAttractionsField;
        
        private bool aEIsMerchantField;
        
        private System.DateTime aEModifyDateField;
        
        /// <remarks/>
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public string BookingLink {
            get {
                return this.bookingLinkField;
            }
            set {
                this.bookingLinkField = value;
            }
        }
        
        /// <remarks/>
        public HotelImage[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public int HotelID {
            get {
                return this.hotelIDField;
            }
            set {
                this.hotelIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double LowRate {
            get {
                return this.lowRateField;
            }
            set {
                this.lowRateField = value;
            }
        }
        
        /// <remarks/>
        public double HighRate {
            get {
                return this.highRateField;
            }
            set {
                this.highRateField = value;
            }
        }
        
        /// <remarks/>
        public string MarketingLevel {
            get {
                return this.marketingLevelField;
            }
            set {
                this.marketingLevelField = value;
            }
        }
        
        /// <remarks/>
        public int Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        public string HotelModified {
            get {
                return this.hotelModifiedField;
            }
            set {
                this.hotelModifiedField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        public string GMTOffset {
            get {
                return this.gMTOffsetField;
            }
            set {
                this.gMTOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string YearPropertyOpened {
            get {
                return this.yearPropertyOpenedField;
            }
            set {
                this.yearPropertyOpenedField = value;
            }
        }
        
        /// <remarks/>
        public string YearPropertyRenovated {
            get {
                return this.yearPropertyRenovatedField;
            }
            set {
                this.yearPropertyRenovatedField = value;
            }
        }
        
        /// <remarks/>
        public string NativeCurrency {
            get {
                return this.nativeCurrencyField;
            }
            set {
                this.nativeCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfRooms {
            get {
                return this.numberOfRoomsField;
            }
            set {
                this.numberOfRoomsField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfSuites {
            get {
                return this.numberOfSuitesField;
            }
            set {
                this.numberOfSuitesField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfFloors {
            get {
                return this.numberOfFloorsField;
            }
            set {
                this.numberOfFloorsField = value;
            }
        }
        
        /// <remarks/>
        public string CheckInTime {
            get {
                return this.checkInTimeField;
            }
            set {
                this.checkInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CheckOutTime {
            get {
                return this.checkOutTimeField;
            }
            set {
                this.checkOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasValetParking {
            get {
                return this.hasValetParkingField;
            }
            set {
                this.hasValetParkingField = value;
            }
        }
        
        /// <remarks/>
        public bool HasContinentalBreakfast {
            get {
                return this.hasContinentalBreakfastField;
            }
            set {
                this.hasContinentalBreakfastField = value;
            }
        }
        
        /// <remarks/>
        public bool HasInRoomMovies {
            get {
                return this.hasInRoomMoviesField;
            }
            set {
                this.hasInRoomMoviesField = value;
            }
        }
        
        /// <remarks/>
        public bool HasSauna {
            get {
                return this.hasSaunaField;
            }
            set {
                this.hasSaunaField = value;
            }
        }
        
        /// <remarks/>
        public bool HasWhirlpool {
            get {
                return this.hasWhirlpoolField;
            }
            set {
                this.hasWhirlpoolField = value;
            }
        }
        
        /// <remarks/>
        public bool HasVoiceMail {
            get {
                return this.hasVoiceMailField;
            }
            set {
                this.hasVoiceMailField = value;
            }
        }
        
        /// <remarks/>
        public bool Has24HourSecurity {
            get {
                return this.has24HourSecurityField;
            }
            set {
                this.has24HourSecurityField = value;
            }
        }
        
        /// <remarks/>
        public bool HasParkingGarage {
            get {
                return this.hasParkingGarageField;
            }
            set {
                this.hasParkingGarageField = value;
            }
        }
        
        /// <remarks/>
        public bool HasElectronicRoomKeys {
            get {
                return this.hasElectronicRoomKeysField;
            }
            set {
                this.hasElectronicRoomKeysField = value;
            }
        }
        
        /// <remarks/>
        public bool HasCoffeeTeaMaker {
            get {
                return this.hasCoffeeTeaMakerField;
            }
            set {
                this.hasCoffeeTeaMakerField = value;
            }
        }
        
        /// <remarks/>
        public bool HasSafe {
            get {
                return this.hasSafeField;
            }
            set {
                this.hasSafeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasVideoCheckOut {
            get {
                return this.hasVideoCheckOutField;
            }
            set {
                this.hasVideoCheckOutField = value;
            }
        }
        
        /// <remarks/>
        public bool HasRestrictedAccess {
            get {
                return this.hasRestrictedAccessField;
            }
            set {
                this.hasRestrictedAccessField = value;
            }
        }
        
        /// <remarks/>
        public bool HasInteriorRoomEntrance {
            get {
                return this.hasInteriorRoomEntranceField;
            }
            set {
                this.hasInteriorRoomEntranceField = value;
            }
        }
        
        /// <remarks/>
        public bool HasExteriorRoomEntrance {
            get {
                return this.hasExteriorRoomEntranceField;
            }
            set {
                this.hasExteriorRoomEntranceField = value;
            }
        }
        
        /// <remarks/>
        public bool HasCombination {
            get {
                return this.hasCombinationField;
            }
            set {
                this.hasCombinationField = value;
            }
        }
        
        /// <remarks/>
        public bool HasFitnessFacility {
            get {
                return this.hasFitnessFacilityField;
            }
            set {
                this.hasFitnessFacilityField = value;
            }
        }
        
        /// <remarks/>
        public bool HasGameRoom {
            get {
                return this.hasGameRoomField;
            }
            set {
                this.hasGameRoomField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTennisCourt {
            get {
                return this.hasTennisCourtField;
            }
            set {
                this.hasTennisCourtField = value;
            }
        }
        
        /// <remarks/>
        public bool HasGolfCourse {
            get {
                return this.hasGolfCourseField;
            }
            set {
                this.hasGolfCourseField = value;
            }
        }
        
        /// <remarks/>
        public bool HasInHouseDining {
            get {
                return this.hasInHouseDiningField;
            }
            set {
                this.hasInHouseDiningField = value;
            }
        }
        
        /// <remarks/>
        public bool HasInHouseBar {
            get {
                return this.hasInHouseBarField;
            }
            set {
                this.hasInHouseBarField = value;
            }
        }
        
        /// <remarks/>
        public bool HasHandicapAccessible {
            get {
                return this.hasHandicapAccessibleField;
            }
            set {
                this.hasHandicapAccessibleField = value;
            }
        }
        
        /// <remarks/>
        public bool HasChildrenAllowed {
            get {
                return this.hasChildrenAllowedField;
            }
            set {
                this.hasChildrenAllowedField = value;
            }
        }
        
        /// <remarks/>
        public bool HasPetsAllowed {
            get {
                return this.hasPetsAllowedField;
            }
            set {
                this.hasPetsAllowedField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTVInRoom {
            get {
                return this.hasTVInRoomField;
            }
            set {
                this.hasTVInRoomField = value;
            }
        }
        
        /// <remarks/>
        public bool HasDataPorts {
            get {
                return this.hasDataPortsField;
            }
            set {
                this.hasDataPortsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMeetingRooms {
            get {
                return this.hasMeetingRoomsField;
            }
            set {
                this.hasMeetingRoomsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasBusinessCenter {
            get {
                return this.hasBusinessCenterField;
            }
            set {
                this.hasBusinessCenterField = value;
            }
        }
        
        /// <remarks/>
        public bool HasDryCleaning {
            get {
                return this.hasDryCleaningField;
            }
            set {
                this.hasDryCleaningField = value;
            }
        }
        
        /// <remarks/>
        public bool HasIndoorPool {
            get {
                return this.hasIndoorPoolField;
            }
            set {
                this.hasIndoorPoolField = value;
            }
        }
        
        /// <remarks/>
        public bool HasOutdoorPool {
            get {
                return this.hasOutdoorPoolField;
            }
            set {
                this.hasOutdoorPoolField = value;
            }
        }
        
        /// <remarks/>
        public bool HasNonSmokingRooms {
            get {
                return this.hasNonSmokingRoomsField;
            }
            set {
                this.hasNonSmokingRoomsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasAirportTransportation {
            get {
                return this.hasAirportTransportationField;
            }
            set {
                this.hasAirportTransportationField = value;
            }
        }
        
        /// <remarks/>
        public bool HasAirConditioning {
            get {
                return this.hasAirConditioningField;
            }
            set {
                this.hasAirConditioningField = value;
            }
        }
        
        /// <remarks/>
        public bool HasClothingIron {
            get {
                return this.hasClothingIronField;
            }
            set {
                this.hasClothingIronField = value;
            }
        }
        
        /// <remarks/>
        public bool HasWakeUpService {
            get {
                return this.hasWakeUpServiceField;
            }
            set {
                this.hasWakeUpServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMiniBarInRoom {
            get {
                return this.hasMiniBarInRoomField;
            }
            set {
                this.hasMiniBarInRoomField = value;
            }
        }
        
        /// <remarks/>
        public bool HasRoomService {
            get {
                return this.hasRoomServiceField;
            }
            set {
                this.hasRoomServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool HasHairDryer {
            get {
                return this.hasHairDryerField;
            }
            set {
                this.hasHairDryerField = value;
            }
        }
        
        /// <remarks/>
        public bool HasCarRentDesk {
            get {
                return this.hasCarRentDeskField;
            }
            set {
                this.hasCarRentDeskField = value;
            }
        }
        
        /// <remarks/>
        public bool HasFamilyRooms {
            get {
                return this.hasFamilyRoomsField;
            }
            set {
                this.hasFamilyRoomsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasKitchen {
            get {
                return this.hasKitchenField;
            }
            set {
                this.hasKitchenField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMap {
            get {
                return this.hasMapField;
            }
            set {
                this.hasMapField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyDescription {
            get {
                return this.propertyDescriptionField;
            }
            set {
                this.propertyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        public string GDSChainCode {
            get {
                return this.gDSChainCodeField;
            }
            set {
                this.gDSChainCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GDSChaincodeName {
            get {
                return this.gDSChaincodeNameField;
            }
            set {
                this.gDSChaincodeNameField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationID {
            get {
                return this.destinationIDField;
            }
            set {
                this.destinationIDField = value;
            }
        }
        
        /// <remarks/>
        public string DrivingDirections {
            get {
                return this.drivingDirectionsField;
            }
            set {
                this.drivingDirectionsField = value;
            }
        }
        
        /// <remarks/>
        public string NearbyAttractions {
            get {
                return this.nearbyAttractionsField;
            }
            set {
                this.nearbyAttractionsField = value;
            }
        }
        
        /// <remarks/>
        public bool AEIsMerchant {
            get {
                return this.aEIsMerchantField;
            }
            set {
                this.aEIsMerchantField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AEModifyDate {
            get {
                return this.aEModifyDateField;
            }
            set {
                this.aEModifyDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.design.americaneagle.com", IsNullable=false)]
    public partial class HotelPagingOptions : System.Web.Services.Protocols.SoapHeader {
        
        private HotelSortField sortFieldField;
        
        private bool sortAscendingField;
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public HotelSortField sortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool sortAscending {
            get {
                return this.sortAscendingField;
            }
            set {
                this.sortAscendingField = value;
            }
        }
        
        /// <remarks/>
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public enum HotelSortField {
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        StateProvince,
        
        /// <remarks/>
        PostalCode,
        
        /// <remarks/>
        Distance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.design.americaneagle.com", IsNullable=false)]
    public partial class ImageOptions : System.Web.Services.Protocols.SoapHeader {
        
        private bool includeImagesField;
        
        private int maxWidthField;
        
        private int maxHeightField;
        
        private int maxThumbnailWidthField;
        
        private int maxThumbnailHeightField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public bool includeImages {
            get {
                return this.includeImagesField;
            }
            set {
                this.includeImagesField = value;
            }
        }
        
        /// <remarks/>
        public int maxWidth {
            get {
                return this.maxWidthField;
            }
            set {
                this.maxWidthField = value;
            }
        }
        
        /// <remarks/>
        public int maxHeight {
            get {
                return this.maxHeightField;
            }
            set {
                this.maxHeightField = value;
            }
        }
        
        /// <remarks/>
        public int maxThumbnailWidth {
            get {
                return this.maxThumbnailWidthField;
            }
            set {
                this.maxThumbnailWidthField = value;
            }
        }
        
        /// <remarks/>
        public int maxThumbnailHeight {
            get {
                return this.maxThumbnailHeightField;
            }
            set {
                this.maxThumbnailHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.design.americaneagle.com", IsNullable=false)]
    public partial class FilterContainer : System.Web.Services.Protocols.SoapHeader {
        
        private HotelFilter[] filtersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public HotelFilter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetHotelCompletedEventHandler(object sender, GetHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SiteScopeCompletedEventHandler(object sender, SiteScopeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SiteScopeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SiteScopeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591